export const BASE_API_URL =  "http://127.0.0.1:1337/api";
export const AUTH_TOKEN =  "e1b4ad01b4bcff4750a619f88306e60299cc2db291ff9e88eff48f63b93f69b0f619bf7a697422766367d8528f9006caa142f7ef64edbf8d779948bd59096d53a60e70aae3c4bc2ecb6570d371e72340e5f0677daaf46ce9cce9ef60a7decf4975a2aa02fad338e292a3e6687c2951a86b5778e475d8121fa11144628b02fe51";
export const description = `Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste voluptate quam tenetur laudantium vel omnis pariatur quia rerum odio. Nobis ad, iusto qui impedit ratione accusantium at doloremque in saepe!
Magni esse tempore reprehenderit nemo hic expedita nisi explicabo, aliquam dolorum qui. Minima aliquam quae doloribus atque animi fugit natus unde error voluptatum nemo! Neque voluptas aspernatur excepturi. Non, nulla?
Et ipsum explicabo eius, sunt vel iste voluptatem, laboriosam suscipit ad natus sit repudiandae recusandae doloribus dolor officia. Voluptate rerum molestias numquam voluptas blanditiis ullam! Eveniet deleniti at repellendus culpa.
Eos, ipsum mollitia excepturi cupiditate nesciunt voluptatem, earum ea debitis architecto obcaecati quo quam laudantium delectus voluptas saepe! Temporibus, sit. Iste exercitationem minima necessitatibus sunt amet, beatae numquam iure natus!
Odio voluptas odit error est quis. Repudiandae, explicabo! Dicta natus maxime quos saepe quibusdam aperiam corporis cupiditate tempora explicabo delectus autem dolorem, doloribus at perferendis repudiandae modi accusamus odio voluptate?
Sapiente reiciendis sint dolorum officia id assumenda inventore ratione odit? Debitis eveniet neque a atque repellendus, autem quia, beatae ipsam ut pariatur voluptatem numquam explicabo ullam nostrum commodi fuga reiciendis?
Laboriosam impedit suscipit quo obcaecati ipsa explicabo inventore iure nulla? At, ipsum rerum. Adipisci pariatur voluptates nemo? Facere aperiam cupiditate temporibus dolores deserunt voluptas ratione, atque deleniti quod, hic ad.
Voluptatem error quisquam fugiat dolor odio id animi sed distinctio neque voluptates mollitia quam ipsum dolorum repellat nam, molestias voluptatibus similique ab natus doloribus nisi. Necessitatibus itaque fuga placeat nam!
Pariatur nihil autem molestias nostrum nam ex minus delectus aliquam quia. Ipsum numquam nisi voluptatem, temporibus, accusamus obcaecati dolorem molestias sequi officiis deleniti at cupiditate optio dicta vel. Illum, eius.
Deserunt, aliquid quia doloremque assumenda corporis unde vero perferendis iure illo maxime voluptas, nesciunt at recusandae magni ipsum reprehenderit aut! Eos possimus laborum aut, perferendis pariatur quos enim officiis atque!
Vel tempore adipisci consequatur aspernatur laboriosam animi officiis sapiente aperiam incidunt beatae accusamus sit ad reiciendis est, corporis rem praesentium veritatis, ratione dolor delectus, alias consequuntur necessitatibus. Ullam, nesciunt impedit.
Reprehenderit, maxime! Fugiat ad aut expedita accusantium, deserunt dolorum officia natus corporis aperiam maiores. Possimus, hic tenetur consequuntur quam voluptas animi sunt repudiandae, ullam reiciendis, eos aperiam voluptates amet odio.
Unde vel quidem quod perferendis commodi consequuntur, dolor veritatis, non iusto, a impedit. Fugiat dolor animi suscipit ad, reiciendis tempore dolorem mollitia vitae perferendis, similique iste blanditiis obcaecati qui quas!
Magni molestiae voluptas laborum corrupti minus nisi optio cum in officia doloribus ratione error fugit sunt, laudantium consectetur provident vel delectus? Quod officia temporibus nisi reiciendis labore perspiciatis necessitatibus quae.
Impedit inventore deleniti illum consectetur est aliquid assumenda quia necessitatibus ducimus porro cum tempora, doloremque suscipit reiciendis. Sint voluptate tempore magnam illo voluptates voluptatibus facere! Neque perferendis blanditiis temporibus quos.
Consequatur asperiores eos, veritatis quo temporibus facilis soluta nobis ab iure quae hic repudiandae nostrum, odio tempora ex. Assumenda earum dolores debitis pariatur distinctio impedit molestiae molestias, culpa autem praesentium!
Ducimus dolorum accusantium iusto corporis cum deserunt incidunt. Eos architecto eligendi incidunt placeat porro nihil cupiditate aspernatur nulla repudiandae earum. Ipsam vel temporibus laudantium eos voluptate odit, in veritatis fugit.
Porro rerum nobis quaerat dolorum corporis sed inventore numquam, eligendi quam mollitia labore, alias optio quod quibusdam nihil eveniet, atque iure autem quia sunt reiciendis culpa expedita. Error, nostrum doloribus.
At corrupti itaque officia inventore tenetur vero illo, ipsam doloribus architecto quibusdam. Quisquam perferendis vel dolorum reiciendis, blanditiis fuga aliquid voluptatem animi, omnis labore explicabo autem iste rem libero architecto.
Eaque nam pariatur, quia maiores soluta, porro saepe voluptatibus praesentium, rerum eius nisi quibusdam nesciunt optio minus repellat incidunt sequi est architecto nemo illo culpa commodi. Assumenda ex veniam ut.`
